In [ ]:
# There Some libraries for doing EDA Automate
1) ydata-profiling
2) Sweetviz
3) Auotviz - note worked properly the command runs but the file note created
4) dtale - Not Compatible with newer python 3.13. versions
5) dataprep - same as dtale

In [9]:
# Automated EDA Techniques
# ydata-profiling is a Python library that automatically creates a complete EDA (Exploratory Data Analysis) report for your dataset.
#Instead of manually writing many plots and analysis commands, it generates everything automatically in one report.

!pip install ydata-profiling

Requirement already satisfied: ydata-profiling in c:\users\anurag\anaconda3\lib\site-packages (4.18.4)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (2.3.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (2.12.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\users\anurag\anaconda3\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (2.3.5)
Requirement already satisfied: minify-html>=0.15.0 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (2.32.5)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (0.14.5)
Requirement already satisfied: typeguard<5,>=4 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (4.5.2)
Requirement already satisfied: imagehash==4.3.2 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\anurag\anaconda3\lib\site-packages (from ydata-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in c:\users\anurag\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in c:\users\anurag\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (12.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\anurag\anaconda3\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\users\anurag\anaconda3\lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\anurag\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anurag\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\anurag\anaconda3\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\anurag\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\anurag\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\anurag\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\anurag\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\anurag\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\anurag\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\anurag\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\anurag\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.1.4)
Requirement already satisfied: patsy>=0.5.6 in c:\users\anurag\anaconda3\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: colorama in c:\users\anurag\anaconda3\lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\anurag\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in c:\users\anurag\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.5)
Requirement already satisfied: puremagic in c:\users\anurag\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\anurag\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

In [13]:
# taken an default dataset from seaborn 
import seaborn as sns 
df = sns.load_dataset('tips')

In [14]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [19]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df,explorative=True)
# explorative=True tells ydata-profiling to generate a more detailed and advanced EDA report.
profile.to_file('output.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|███████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 367.95it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [21]:
# Auotmating the nextflix dataset
import pandas as pd
df = pd.read_csv("netflix.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [22]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df,explorative=True)
# explorative=True tells ydata-profiling to generate a more detailed and advanced EDA report.
profile.to_file('nextflix-report.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|                                                                                           | 0/12 [00:00<?, ?it/s]
  8%|██████▉                                                                            | 1/12 [00:04<00:51,  4.64s/it]
 33%|███████████████████████████▋                                                       | 4/12 [00:05<00:09,  1.22s/it]
 42%|██████████████████████████████████▌                                                | 5/12 [00:06<00:08,  1.15s/it]
 50%|█████████████████████████████████████████▌                                         | 6/12 [00:07<00:05,  1.16it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:07<00:00,  1.58it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [1]:
# Auotmating the titanic dataset
import pandas as pd
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
from ydata_profiling import ProfileReport
profile = ProfileReport(df,explorative=True)
profile.to_file('titanic-report.html')

C:\Users\Anurag\AppData\Local\Temp\ipykernel_1116\3566123126.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|                                                                                           | 0/12 [00:00<?, ?it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 64.05it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
!pip install sweetviz

Collecting sweetviz
  Downloading sweetviz-2.3.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in c:\users\anurag\anaconda3\lib\site-packages (from sweetviz) (2.3.3)
Requirement already satisfied: numpy>=1.16.0 in c:\users\anurag\anaconda3\lib\site-packages (from sweetviz) (2.3.5)
Requirement already satisfied: matplotlib>=3.1.3 in c:\users\anurag\anaconda3\lib\site-packages (from sweetviz) (3.10.0)
Requirement already satisfied: tqdm>=4.43.0 in c:\users\anurag\anaconda3\lib\site-packages (from sweetviz) (4.67.1)
Requirement already satisfied: scipy>=1.3.2 in c:\users\anurag\anaconda3\lib\site-packages (from sweetviz) (1.16.3)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\anurag\anaconda3\lib\site-packages (from sweetviz) (3.1.6)
Collecting importlib_resources>=1.2.0 (from sweetviz)
  Downloading importlib_resources-7.1.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\anurag\anaconda3\lib\site-packages (from jinja2>=2.11.1->sweetviz) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\anurag\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anurag\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\anurag\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Requirement already satisfied: colorama in c:\users\anurag\anaconda3\lib\site-packages (from tqdm>=4.43.0->sweetviz) (0.4.6)
Downloading sweetviz-2.3.3-py3-none-any.whl (15.1 MB)
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/15.1 MB 126.3 kB/s eta 0:01:56
   - -------------------------------------- 0.5/15.1 MB 126.3 kB/s eta 0:01:56
   - -------------------------------------- 0.5/15.1 MB 126.3 kB/s eta 0:01:56
   - -------------------------------------- 0.5/15.1 MB 126.3 kB/s eta 0:01:56
   - -------------------------------------- 0.5/15.1 MB 126.3 kB/s eta 0:01:56
   - -------------------------------------- 0.5/15.1 MB 126.3 kB/s eta 0:01:56
   - -------------------------------------- 0.5/15.1 MB 126.3 kB/s eta 0:01:56
   - -------------------------------------- 0.5/15.1 MB 126.3 kB/s eta 0:01:56
   - -------------------------------------- 0.5/15.1 MB 126.3 kB/s eta 0:01:56
   - -------------------------------------- 0.5/15.1 MB 126.3 kB/s eta 0:01:56
   - -------------------------------------- 0.5/15.1 MB 126.3 kB/s eta 0:01:56
   - -------------------------------------- 0.5/15.1 MB 126.3 kB/s eta 0:01:56
   - -------------------------------------- 0.5/15.1 MB 126.3 kB/s eta 0:01:56
   - -------------------------------------- 0.5/15.1 MB 126.3 kB/s eta 0:01:56
   - -------------------------------------- 0.5/15.1 MB 126.3 kB/s eta 0:01:56
   -- ------------------------------------- 0.8/15.1 MB 100.2 kB/s eta 0:02:24
   -- ------------------------------------- 0.8/15.1 MB 100.2 kB/s eta 0:02:24
   -- ------------------------------------- 0.8/15.1 MB 100.2 kB/s eta 0:02:24
   -- ------------------------------------- 0.8/15.1 MB 100.2 kB/s eta 0:02:24
   -- ------------------------------------- 0.8/15.1 MB 100.2 kB/s eta 0:02:24
   -- ------------------------------------- 0.8/15.1 MB 100.2 kB/s eta 0:02:24
   -- ------------------------------------- 0.8/15.1 MB 100.2 kB/s eta 0:02:24
   -- ------------------------------------- 0.8/15.1 MB 100.2 kB/s eta 0:02:24
   -- ------------------------------------- 0.8/15.1 MB 100.2 kB/s eta 0:02:24
   -- ------------------------------------- 0.8/15.1 MB 100.2 kB/s eta 0:02:24
   -- ------------------------------------- 0.8/15.1 MB 100.2 kB/s eta 0:02:24
   -- ------------------------------------- 0.8/15.1 MB 100.2 kB/s eta 0:02:24
   -- ------------------------------------- 0.8/15.1 MB 100.2 kB/s eta 0:02:24
   -- ------------------------------------- 0.8/15.1 MB 100.2 kB/s eta 0:02:24
   -- ------------------------------------- 1.0/15.1 MB 94.1 kB/s eta 0:02:30
   -- ------------------------------------- 1.0/15.1 MB 94.1 kB/s eta 0:02:30
   -- ------------------------------------- 1.0/15.1 MB 94.1 kB/s eta 0:02:30
   -- ------------------------------------- 1.0/15.1 MB 94.1 kB/s eta 0:02:30
   -- ------------------------------------- 1.0/15.1 MB 94.1 kB/s eta 0:02:30
   -- ------------------------------------- 1.0/15.1 MB 94.1 kB/s eta 0:02:30
   -- ------------------------------------- 1.0/15.1 MB 94.1 kB/s eta 0:02:30
   -- ------------------------------------- 1.0/15.1 MB 94.1 kB/s eta 0:02:30
   -- ------------------------------------- 1.0/15.1 MB 94.1 kB/s eta 0:02:30
   --- ------------------------------------ 1.3/15.1 MB 101.7 kB/s eta 0:02:16
   --- ------------------------------------ 1.3/15.1 MB 101.7 kB/s eta 0:02:16
   --- ------------------------------------ 1.3/15.1 MB 101.7 kB/s eta 0:02:16
   --- ------------------------------------ 1.3/15.1 MB 101.7 kB/s eta 0:02:16
   --- ------------------------------------ 1.3/15.1 MB 101.7 kB/s eta 0:02:16
   --- ------------------------------------ 1.3/15.1 MB 101.7 kB/s eta 0:02:16
   --- ------------------------------------ 1.3/15.1 MB 101.7 kB/s eta 0:02:16
   ---- ----------------------------------- 1.6/15.1 MB 109.3 kB/s eta 0:02:04
   ---- ----------------------------------- 1.6/15.1 MB 109.3 kB/s eta 0:02:04
   ---- ----------------------------------- 1.6/15.1 MB 109.3 kB/s eta 0:02:04
   ---- ----------------------------------- 1.6/15.1 MB 109.3 kB/s eta 0:02:04
   ---- ----------------------------------- 1.6/15.1 MB 109.3 kB/s eta 0:02:04
   ---- ----------------------------------- 1.6/15.1 MB 109.3 kB/s eta 0:02:04
   ---- ----------------------------------- 1.6/15.1 MB 109.3 kB/s eta 0:02:04
   ---- ----------------------------------- 1.6/15.1 MB 109.3 kB/s eta 0:02:04
   ---- ----------------------------------- 1.8/15.1 MB 114.6 kB/s eta 0:01:56
   ---- ----------------------------------- 1.8/15.1 MB 114.6 kB/s eta 0:01:56
   ---- ----------------------------------- 1.8/15.1 MB 114.6 kB/s eta 0:01:56
   ---- ----------------------------------- 1.8/15.1 MB 114.6 kB/s eta 0:01:56
   ---- ----------------------------------- 1.8/15.1 MB 114.6 kB/s eta 0:01:56
   ---- ----------------------------------- 1.8/15.1 MB 114.6 kB/s eta 0:01:56
   ---- ----------------------------------- 1.8/15.1 MB 114.6 kB/s eta 0:01:56
   ---- ----------------------------------- 1.8/15.1 MB 114.6 kB/s eta 0:01:56
   ---- ----------------------------------- 1.8/15.1 MB 114.6 kB/s eta 0:01:56
   ---- ----------------------------------- 1.8/15.1 MB 114.6 kB/s eta 0:01:56
   ---- ----------------------------------- 1.8/15.1 MB 114.6 kB/s eta 0:01:56
   ---- ----------------------------------- 1.8/15.1 MB 114.6 kB/s eta 0:01:56
   ---- ----------------------------------- 1.8/15.1 MB 114.6 kB/s eta 0:01:56
   ----- ---------------------------------- 2.1/15.1 MB 111.4 kB/s eta 0:01:57
   ----- ---------------------------------- 2.1/15.1 MB 111.4 kB/s eta 0:01:57
   ----- ---------------------------------- 2.1/15.1 MB 111.4 kB/s eta 0:01:57
   ----- ---------------------------------- 2.1/15.1 MB 111.4 kB/s eta 0:01:57
   ----- ---------------------------------- 2.1/15.1 MB 111.4 kB/s eta 0:01:57
   ----- ---------------------------------- 2.1/15.1 MB 111.4 kB/s eta 0:01:57
   ----- ---------------------------------- 2.1/15.1 MB 111.4 kB/s eta 0:01:57
   ----- ---------------------------------- 2.1/15.1 MB 111.4 kB/s eta 0:01:57
   ----- ---------------------------------- 2.1/15.1 MB 111.4 kB/s eta 0:01:57
   ----- ---------------------------------- 2.1/15.1 MB 111.4 kB/s eta 0:01:57
   ----- ---------------------------------- 2.1/15.1 MB 111.4 kB/s eta 0:01:57
   ----- ---------------------------------- 2.1/15.1 MB 111.4 kB/s eta 0:01:57
   ------ --------------------------------- 2.4/15.1 MB 109.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.4/15.1 MB 109.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.4/15.1 MB 109.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.4/15.1 MB 109.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.4/15.1 MB 109.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.4/15.1 MB 109.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.4/15.1 MB 109.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.4/15.1 MB 109.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.4/15.1 MB 109.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.4/15.1 MB 109.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.4/15.1 MB 109.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.4/15.1 MB 109.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.4/15.1 MB 109.6 kB/s eta 0:01:57
   ------ --------------------------------- 2.6/15.1 MB 108.3 kB/s eta 0:01:56
   ------ --------------------------------- 2.6/15.1 MB 108.3 kB/s eta 0:01:56
   ------ --------------------------------- 2.6/15.1 MB 108.3 kB/s eta 0:01:56
   ------ --------------------------------- 2.6/15.1 MB 108.3 kB/s eta 0:01:56
   ------ --------------------------------- 2.6/15.1 MB 108.3 kB/s eta 0:01:56
   ------ --------------------------------- 2.6/15.1 MB 108.3 kB/s eta 0:01:56
   ------ --------------------------------- 2.6/15.1 MB 108.3 kB/s eta 0:01:56
   ------ --------------------------------- 2.6/15.1 MB 108.3 kB/s eta 0:01:56
   ------ --------------------------------- 2.6/15.1 MB 108.3 kB/s eta 0:01:56
   ------- -------------------------------- 2.9/15.1 MB 110.5 kB/s eta 0:01:51
   ------- -------------------------------- 2.9/15.1 MB 110.5 kB/s eta 0:01:51
   ------- -------------------------------- 2.9/15.1 MB 110.5 kB/s eta 0:01:51
   ------- -------------------------------- 2.9/15.1 MB 110.5 kB/s eta 0:01:51
   ------- -------------------------------- 2.9/15.1 MB 110.5 kB/s eta 0:01:51
   ------- -------------------------------- 2.9/15.1 MB 110.5 kB/s eta 0:01:51
   ------- -------------------------------- 2.9/15.1 MB 110.5 kB/s eta 0:01:51
   ------- -------------------------------- 2.9/15.1 MB 110.5 kB/s eta 0:01:51
   ------- -------------------------------- 2.9/15.1 MB 110.5 kB/s eta 0:01:51
   ------- -------------------------------- 2.9/15.1 MB 110.5 kB/s eta 0:01:51
   -------- ------------------------------- 3.1/15.1 MB 111.2 kB/s eta 0:01:48
   -------- ------------------------------- 3.1/15.1 MB 111.2 kB/s eta 0:01:48
   -------- ------------------------------- 3.1/15.1 MB 111.2 kB/s eta 0:01:48
   --------- ------------------------------ 3.4/15.1 MB 118.4 kB/s eta 0:01:39
   --------- ------------------------------ 3.4/15.1 MB 118.4 kB/s eta 0:01:39
   --------- ------------------------------ 3.4/15.1 MB 118.4 kB/s eta 0:01:39
   --------- ------------------------------ 3.4/15.1 MB 118.4 kB/s eta 0:01:39
   --------- ------------------------------ 3.7/15.1 MB 123.4 kB/s eta 0:01:33
   --------- ------------------------------ 3.7/15.1 MB 123.4 kB/s eta 0:01:33
   --------- ------------------------------ 3.7/15.1 MB 123.4 kB/s eta 0:01:33
   --------- ------------------------------ 3.7/15.1 MB 123.4 kB/s eta 0:01:33
   --------- ------------------------------ 3.7/15.1 MB 123.4 kB/s eta 0:01:33
   --------- ------------------------------ 3.7/15.1 MB 123.4 kB/s eta 0:01:33
   --------- ------------------------------ 3.7/15.1 MB 123.4 kB/s eta 0:01:33
   --------- ------------------------------ 3.7/15.1 MB 123.4 kB/s eta 0:01:33
   ---------- ----------------------------- 3.9/15.1 MB 125.5 kB/s eta 0:01:30
   ---------- ----------------------------- 3.9/15.1 MB 125.5 kB/s eta 0:01:30
   ---------- ----------------------------- 3.9/15.1 MB 125.5 kB/s eta 0:01:30
   ----------- ---------------------------- 4.2/15.1 MB 131.2 kB/s eta 0:01:24
   ----------- ---------------------------- 4.2/15.1 MB 131.2 kB/s eta 0:01:24
   ----------- ---------------------------- 4.2/15.1 MB 131.2 kB/s eta 0:01:24
   ----------- ---------------------------- 4.2/15.1 MB 131.2 kB/s eta 0:01:24
   ----------- ---------------------------- 4.2/15.1 MB 131.2 kB/s eta 0:01:24
   ----------- ---------------------------- 4.5/15.1 MB 136.0 kB/s eta 0:01:19
   ----------- ---------------------------- 4.5/15.1 MB 136.0 kB/s eta 0:01:19
   ----------- ---------------------------- 4.5/15.1 MB 136.0 kB/s eta 0:01:19
   ----------- ---------------------------- 4.5/15.1 MB 136.0 kB/s eta 0:01:19
   ----------- ---------------------------- 4.5/15.1 MB 136.0 kB/s eta 0:01:19
   ----------- ---------------------------- 4.5/15.1 MB 136.0 kB/s eta 0:01:19
   ----------- ---------------------------- 4.5/15.1 MB 136.0 kB/s eta 0:01:19
   ----------- ---------------------------- 4.5/15.1 MB 136.0 kB/s eta 0:01:19
   ----------- ---------------------------- 4.5/15.1 MB 136.0 kB/s eta 0:01:19
   ----------- ---------------------------- 4.5/15.1 MB 136.0 kB/s eta 0:01:19
   ------------ --------------------------- 4.7/15.1 MB 140.3 kB/s eta 0:01:15
   ------------ --------------------------- 4.7/15.1 MB 140.3 kB/s eta 0:01:15
   ------------ --------------------------- 4.7/15.1 MB 140.3 kB/s eta 0:01:15
   ------------ --------------------------- 4.7/15.1 MB 140.3 kB/s eta 0:01:15
   ------------- -------------------------- 5.0/15.1 MB 145.3 kB/s eta 0:01:10
   ------------- -------------------------- 5.0/15.1 MB 145.3 kB/s eta 0:01:10
   ------------- -------------------------- 5.2/15.1 MB 152.7 kB/s eta 0:01:05
   -------------- ------------------------- 5.5/15.1 MB 160.1 kB/s eta 0:01:01
   -------------- ------------------------- 5.5/15.1 MB 160.1 kB/s eta 0:01:01
   --------------- ------------------------ 5.8/15.1 MB 175.4 kB/s eta 0:00:54
   --------------- ------------------------ 5.8/15.1 MB 175.4 kB/s eta 0:00:54
   --------------- ------------------------ 5.8/15.1 MB 175.4 kB/s eta 0:00:54
   --------------- ------------------------ 6.0/15.1 MB 182.0 kB/s eta 0:00:50
   ---------------- ----------------------- 6.3/15.1 MB 188.7 kB/s eta 0:00:47
   ---------------- ----------------------- 6.3/15.1 MB 188.7 kB/s eta 0:00:47
   ----------------- ---------------------- 6.6/15.1 MB 195.6 kB/s eta 0:00:44
   ------------------ --------------------- 6.8/15.1 MB 203.1 kB/s eta 0:00:41
   ------------------ --------------------- 7.1/15.1 MB 210.4 kB/s eta 0:00:39
   ------------------ --------------------- 7.1/15.1 MB 210.4 kB/s eta 0:00:39
   ------------------- -------------------- 7.3/15.1 MB 216.9 kB/s eta 0:00:36
   -------------------- ------------------- 7.6/15.1 MB 223.4 kB/s eta 0:00:34
   -------------------- ------------------- 7.6/15.1 MB 223.4 kB/s eta 0:00:34
   -------------------- ------------------- 7.9/15.1 MB 230.1 kB/s eta 0:00:32
   --------------------- ------------------ 8.1/15.1 MB 236.8 kB/s eta 0:00:30
   --------------------- ------------------ 8.1/15.1 MB 236.8 kB/s eta 0:00:30
   --------------------- ------------------ 8.1/15.1 MB 236.8 kB/s eta 0:00:30
   ---------------------- ----------------- 8.4/15.1 MB 248.1 kB/s eta 0:00:28
   ---------------------- ----------------- 8.4/15.1 MB 248.1 kB/s eta 0:00:28
   ---------------------- ----------------- 8.4/15.1 MB 248.1 kB/s eta 0:00:28
   ---------------------- ----------------- 8.7/15.1 MB 251.8 kB/s eta 0:00:26
   ---------------------- ----------------- 8.7/15.1 MB 251.8 kB/s eta 0:00:26
   ---------------------- ----------------- 8.7/15.1 MB 251.8 kB/s eta 0:00:26
   ---------------------- ----------------- 8.7/15.1 MB 251.8 kB/s eta 0:00:26
   ---------------------- ----------------- 8.7/15.1 MB 251.8 kB/s eta 0:00:26
   ---------------------- ----------------- 8.7/15.1 MB 251.8 kB/s eta 0:00:26
   ---------------------- ----------------- 8.7/15.1 MB 251.8 kB/s eta 0:00:26
   ---------------------- ----------------- 8.7/15.1 MB 251.8 kB/s eta 0:00:26
   ----------------------- ---------------- 8.9/15.1 MB 251.2 kB/s eta 0:00:25
   ----------------------- ---------------- 8.9/15.1 MB 251.2 kB/s eta 0:00:25
   ----------------------- ---------------- 8.9/15.1 MB 251.2 kB/s eta 0:00:25
   ----------------------- ---------------- 8.9/15.1 MB 251.2 kB/s eta 0:00:25
   ----------------------- ---------------- 8.9/15.1 MB 251.2 kB/s eta 0:00:25
   ----------------------- ---------------- 8.9/15.1 MB 251.2 kB/s eta 0:00:25
   ----------------------- ---------------- 8.9/15.1 MB 251.2 kB/s eta 0:00:25
   ----------------------- ---------------- 8.9/15.1 MB 251.2 kB/s eta 0:00:25
   ----------------------- ---------------- 8.9/15.1 MB 251.2 kB/s eta 0:00:25
   ----------------------- ---------------- 8.9/15.1 MB 251.2 kB/s eta 0:00:25
   ----------------------- ---------------- 8.9/15.1 MB 251.2 kB/s eta 0:00:25
   ----------------------- ---------------- 8.9/15.1 MB 251.2 kB/s eta 0:00:25
   ----------------------- ---------------- 8.9/15.1 MB 251.2 kB/s eta 0:00:25
   ----------------------- ---------------- 8.9/15.1 MB 251.2 kB/s eta 0:00:25

In [13]:
import sweetviz as sv
df = pd.read_csv('titanic.csv')
report= sv.analyze(df)
report.show_html('sweetviz-titanic-report.html')

                                             |                                             | [  0%]   00:00 ->…

Report sweetviz-titanic-report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [5]:
!pip install autoviz

Collecting autoviz
  Using cached autoviz-0.1.905-py3-none-any.whl.metadata (14 kB)
Collecting xlrd (from autoviz)
  Using cached xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: wordcloud in c:\users\anurag\anaconda3\lib\site-packages (from autoviz) (1.9.6)
Collecting emoji (from autoviz)
  Using cached emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Collecting pyamg (from autoviz)
  Using cached pyamg-5.3.0-cp313-cp313-win_amd64.whl.metadata (8.3 kB)
Requirement already satisfied: scikit-learn in c:\users\anurag\anaconda3\lib\site-packages (from autoviz) (1.7.2)
Requirement already satisfied: statsmodels in c:\users\anurag\anaconda3\lib\site-packages (from autoviz) (0.14.5)
Requirement already satisfied: nltk in c:\users\anurag\anaconda3\lib\site-packages (from autoviz) (3.9.2)
Collecting textblob (from autoviz)
  Using cached textblob-0.20.0-py3-none-any.whl.metadata (4.0 kB)
Collecting xgboost<1.7,>=0.82 (from autoviz)
  Using cached xgboost-1.6.2-py3-none-win_amd64.whl.metadata (1.8 kB)
Requirement already satisfied: fsspec>=0.8.3 in c:\users\anurag\anaconda3\lib\site-packages (from autoviz) (2025.10.0)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\anurag\anaconda3\lib\site-packages (from autoviz) (4.15.0)
Collecting pandas-dq>=1.29 (from autoviz)
  Using cached pandas_dq-1.29-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.24.0 in c:\users\anurag\anaconda3\lib\site-packages (from autoviz) (2.3.5)
Requirement already satisfied: hvplot>=0.9.2 in c:\users\anurag\anaconda3\lib\site-packages (from autoviz) (0.12.1)
Requirement already satisfied: holoviews>=1.16.0 in c:\users\anurag\anaconda3\lib\site-packages (from autoviz) (1.22.0)
Requirement already satisfied: panel>=1.4.0 in c:\users\anurag\anaconda3\lib\site-packages (from autoviz) (1.8.3)
Requirement already satisfied: pandas>=2.0 in c:\users\anurag\anaconda3\lib\site-packages (from autoviz) (2.3.3)
Requirement already satisfied: matplotlib>3.7.4 in c:\users\anurag\anaconda3\lib\site-packages (from autoviz) (3.10.0)
Requirement already satisfied: seaborn>0.12.2 in c:\users\anurag\anaconda3\lib\site-packages (from autoviz) (0.13.2)
Requirement already satisfied: scipy in c:\users\anurag\anaconda3\lib\site-packages (from xgboost<1.7,>=0.82->autoviz) (1.16.3)
Requirement already satisfied: bokeh>=3.1 in c:\users\anurag\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (3.8.0)
Requirement already satisfied: colorcet in c:\users\anurag\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (3.1.0)
Requirement already satisfied: narwhals>=2 in c:\users\anurag\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (2.7.0)
Requirement already satisfied: packaging in c:\users\anurag\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (25.0)
Requirement already satisfied: param<3.0,>=2.0 in c:\users\anurag\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (2.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\anurag\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (2.9.0.post0)
Requirement already satisfied: pyviz-comms>=2.1 in c:\users\anurag\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (3.0.6)
Requirement already satisfied: Jinja2>=2.9 in c:\users\anurag\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in c:\users\anurag\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (1.3.3)
Requirement already satisfied: pillow>=7.1.0 in c:\users\anurag\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (12.0.0)
Requirement already satisfied: PyYAML>=3.10 in c:\users\anurag\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.0.3)
Requirement already satisfied: tornado>=6.2 in c:\users\anurag\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.5.1)
Requirement already satisfied: xyzservices>=2021.09.1 in c:\users\anurag\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (2025.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\anurag\anaconda3\lib\site-packages (from Jinja2>=2.9->bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.0.2)
Requirement already satisfied: cycler>=0.10 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\anurag\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (3.2.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\anurag\anaconda3\lib\site-packages (from pandas>=2.0->autoviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anurag\anaconda3\lib\site-packages (from pandas>=2.0->autoviz) (2025.2)
Requirement already satisfied: bleach in c:\users\anurag\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (6.3.0)
Requirement already satisfied: linkify-it-py in c:\users\anurag\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (2.0.3)
Requirement already satisfied: markdown in c:\users\anurag\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (3.8)
Requirement already satisfied: markdown-it-py in c:\users\anurag\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\users\anurag\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (0.5.0)
Requirement already satisfied: requests in c:\users\anurag\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (2.32.5)
Requirement already satisfied: tqdm in c:\users\anurag\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (4.67.1)
Requirement already satisfied: six>=1.5 in c:\users\anurag\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->holoviews>=1.16.0->autoviz) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\anurag\anaconda3\lib\site-packages (from scikit-learn->autoviz) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\anurag\anaconda3\lib\site-packages (from scikit-learn->autoviz) (3.5.0)
Requirement already satisfied: webencodings in c:\users\anurag\anaconda3\lib\site-packages (from bleach->panel>=1.4.0->autoviz) (0.5.1)
Requirement already satisfied: uc-micro-py in c:\users\anurag\anaconda3\lib\site-packages (from linkify-it-py->panel>=1.4.0->autoviz) (1.0.3)
Requirement already satisfied: mdurl~=0.1 in c:\users\anurag\anaconda3\lib\site-packages (from markdown-it-py->panel>=1.4.0->autoviz) (0.1.2)
Requirement already satisfied: click in c:\users\anurag\anaconda3\lib\site-packages (from nltk->autoviz) (8.2.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\anurag\anaconda3\lib\site-packages (from nltk->autoviz) (2025.9.1)
Requirement already satisfied: colorama in c:\users\anurag\anaconda3\lib\site-packages (from click->nltk->autoviz) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\anurag\anaconda3\lib\site-packages (from requests->panel>=1.4.0->autoviz) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\anurag\anaconda3\lib\site-packages (from requests->panel>=1.4.0->autoviz) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\anurag\anaconda3\lib\site-packages (from requests->panel>=1.4.0->autoviz) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\anurag\anaconda3\lib\site-packages (from requests->panel>=1.4.0->autoviz) (2026.1.4)
Requirement already satisfied: patsy>=0.5.6 in c:\users\anurag\anaconda3\lib\site-packages (from statsmodels->autoviz) (1.0.1)
Using cached autoviz-0.1.905-py3-none-any.whl (67 kB)
Downloading xgboost-1.6.2-py3-none-win_amd64.whl (125.4 MB)
   ---------------------------------------- 0.0/125.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/125.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/125.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/125.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/125.4 MB ? eta -:--:--
   ---------------------------------------- 0.5/125.4 MB 622.6 kB/s eta 0:03:21
   ---------------------------------------- 0.8/125.4 MB 817.9 kB/s eta 0:02:33
   ---------------------------------------- 0.8/125.4 MB 817.9 kB/s eta 0:02:33
   ---------------------------------------- 1.0/125.4 MB 788.9 kB/s eta 0:02:38
   ---------------------------------------- 1.0/125.4 MB 788.9 kB/s eta 0:02:38
   ---------------------------------------- 1.3/125.4 MB 701.6 kB/s eta 0:02:57
   ---------------------------------------- 1.3/125.4 MB 701.6 kB/s eta 0:02:57
    --------------------------------------- 1.6/125.4 MB 708.1 kB/s eta 0:02:55
    --------------------------------------- 1.6/125.4 MB 708.1 kB/s eta 0:02:55
    --------------------------------------- 1.8/125.4 MB 642.4 kB/s eta 0:03:13
    --------------------------------------- 1.8/125.4 MB 642.4 kB/s eta 0:03:13
    --------------------------------------- 1.8/125.4 MB 642.4 kB/s eta 0:03:13
    --------------------------------------- 1.8/125.4 MB 642.4 kB/s eta 0:03:13
    --------------------------------------- 2.1/125.4 MB 574.8 kB/s eta 0:03:35
    --------------------------------------- 2.4/125.4 MB 622.4 kB/s eta 0:03:18
    --------------------------------------- 2.4/125.4 MB 622.4 kB/s eta 0:03:18
    --------------------------------------- 2.4/125.4 MB 622.4 kB/s eta 0:03:18
    --------------------------------------- 2.6/125.4 MB 586.6 kB/s eta 0:03:30
    --------------------------------------- 2.6/125.4 MB 586.6 kB/s eta 0:03:30
    --------------------------------------- 2.6/125.4 MB 586.6 kB/s eta 0:03:30
    --------------------------------------- 2.6/125.4 MB 586.6 kB/s eta 0:03:30
    --------------------------------------- 2.6/125.4 MB 586.6 kB/s eta 0:03:30
    --------------------------------------- 2.6/125.4 MB 586.6 kB/s eta 0:03:30
    --------------------------------------- 2.6/125.4 MB 586.6 kB/s eta 0:03:30
   - -------------------------------------- 3.1/125.4 MB 510.4 kB/s eta 0:04:00
   - -------------------------------------- 3.1/125.4 MB 510.4 kB/s eta 0:04:00
   - -------------------------------------- 3.4/125.4 MB 522.8 kB/s eta 0:03:54
   - -------------------------------------- 3.7/125.4 MB 532.8 kB/s eta 0:03:49
   - -------------------------------------- 3.7/125.4 MB 532.8 kB/s eta 0:03:49
   - -------------------------------------- 3.7/125.4 MB 532.8 kB/s eta 0:03:49
   - -------------------------------------- 3.9/125.4 MB 529.4 kB/s eta 0:03:50
   - -------------------------------------- 3.9/125.4 MB 529.4 kB/s eta 0:03:50
   - -------------------------------------- 4.2/125.4 MB 538.9 kB/s eta 0:03:46
   - -------------------------------------- 4.2/125.4 MB 538.9 kB/s eta 0:03:46
   - -------------------------------------- 4.5/125.4 MB 545.3 kB/s eta 0:03:42
   - -------------------------------------- 4.7/125.4 MB 554.5 kB/s eta 0:03:38
   - -------------------------------------- 4.7/125.4 MB 554.5 kB/s eta 0:03:38
   - -------------------------------------- 5.0/125.4 MB 562.9 kB/s eta 0:03:34
   - -------------------------------------- 5.0/125.4 MB 562.9 kB/s eta 0:03:34
   - -------------------------------------- 5.2/125.4 MB 566.4 kB/s eta 0:03:33
   - -------------------------------------- 5.5/125.4 MB 573.2 kB/s eta 0:03:30
   - -------------------------------------- 5.8/125.4 MB 589.1 kB/s eta 0:03:24
   - -------------------------------------- 5.8/125.4 MB 589.1 kB/s eta 0:03:24
   - -------------------------------------- 6.0/125.4 MB 594.0 kB/s eta 0:03:22
   -- ------------------------------------- 6.3/125.4 MB 598.5 kB/s eta 0:03:20
   -- ------------------------------------- 6.3/125.4 MB 598.5 kB/s eta 0:03:20
   -- ------------------------------------- 6.6/125.4 MB 602.9 kB/s eta 0:03:18
   -- ------------------------------------- 6.6/125.4 MB 602.9 kB/s eta 0:03:18
   -- ------------------------------------- 6.6/125.4 MB 602.9 kB/s eta 0:03:18
   -- ------------------------------------- 6.8/125.4 MB 596.8 kB/s eta 0:03:19
   -- ------------------------------------- 7.1/125.4 MB 600.2 kB/s eta 0:03:18
   -- ------------------------------------- 7.1/125.4 MB 600.2 kB/s eta 0:03:18
   -- ------------------------------------- 7.1/125.4 MB 600.2 kB/s eta 0:03:18
   -- ------------------------------------- 7.3/125.4 MB 593.0 kB/s eta 0:03:20
   -- ------------------------------------- 7.3/125.4 MB 593.0 kB/s eta 0:03:20
   -- ------------------------------------- 7.6/125.4 MB 588.9 kB/s eta 0:03:21
   -- ------------------------------------- 7.6/125.4 MB 588.9 kB/s eta 0:03:21
   -- ------------------------------------- 7.6/125.4 MB 588.9 kB/s eta 0:03:21
   -- ------------------------------------- 7.9/125.4 MB 583.1 kB/s eta 0:03:22
   -- ------------------------------------- 7.9/125.4 MB 583.1 kB/s eta 0:03:22
   -- ------------------------------------- 8.1/125.4 MB 588.9 kB/s eta 0:03:20
   -- ------------------------------------- 8.4/125.4 MB 589.6 kB/s eta 0:03:19
   -- ------------------------------------- 8.4/125.4 MB 589.6 kB/s eta 0:03:19
   -- ------------------------------------- 8.7/125.4 MB 590.8 kB/s eta 0:03:18
   -- ------------------------------------- 8.7/125.4 MB 590.8 kB/s eta 0:03:18
   -- ------------------------------------- 8.9/125.4 MB 592.0 kB/s eta 0:03:17
   -- ------------------------------------- 8.9/125.4 MB 592.0 kB/s eta 0:03:17
   -- ------------------------------------- 8.9/125.4 MB 592.0 kB/s eta 0:03:17
   -- ------------------------------------- 9.2/125.4 MB 584.2 kB/s eta 0:03:20
   -- ------------------------------------- 9.2/125.4 MB 584.2 kB/s eta 0:03:20
   -- ------------------------------------- 9.2/125.4 MB 584.2 kB/s eta 0:03:20
   -- ------------------------------------- 9.2/125.4 MB 584.2 kB/s eta 0:03:20
   -- ------------------------------------- 9.2/125.4 MB 584.2 kB/s eta 0:03:20
   --- ------------------------------------ 9.4/125.4 MB 563.6 kB/s eta 0:03:26
   --- ------------------------------------ 9.7/125.4 MB 573.3 kB/s eta 0:03:22
   --- ------------------------------------ 9.7/125.4 MB 573.3 kB/s eta 0:03:22
   --- ----------------------------------- 10.0/125.4 MB 572.3 kB/s eta 0:03:22
   --- ----------------------------------- 10.0/125.4 MB 572.3 kB/s eta 0:03:22
   --- ----------------------------------- 10.2/125.4 MB 571.7 kB/s eta 0:03:22
   --- ----------------------------------- 10.2/125.4 MB 571.7 kB/s eta 0:03:22
   --- ----------------------------------- 10.5/125.4 MB 574.0 kB/s eta 0:03:21
   --- ----------------------------------- 10.7/125.4 MB 579.8 kB/s eta 0:03:18
   --- ----------------------------------- 11.0/125.4 MB 586.7 kB/s eta 0:03:16
   --- ----------------------------------- 11.0/125.4 MB 586.7 kB/s eta 0:03:16
   --- ----------------------------------- 11.3/125.4 MB 590.5 kB/s eta 0:03:14
   --- ----------------------------------- 11.3/125.4 MB 590.5 kB/s eta 0:03:14
   --- ----------------------------------- 11.5/125.4 MB 589.7 kB/s eta 0:03:14
   --- ----------------------------------- 11.8/125.4 MB 594.1 kB/s eta 0:03:12
   --- ----------------------------------- 11.8/125.4 MB 594.1 kB/s eta 0:03:12
   --- ----------------------------------- 12.1/125.4 MB 592.6 kB/s eta 0:03:12
   --- ----------------------------------- 12.1/125.4 MB 592.6 kB/s eta 0:03:12
   --- ----------------------------------- 12.3/125.4 MB 594.7 kB/s eta 0:03:11
   --- ----------------------------------- 12.3/125.4 MB 594.7 kB/s eta 0:03:11
   --- ----------------------------------- 12.6/125.4 MB 593.6 kB/s eta 0:03:11
   --- ----------------------------------- 12.6/125.4 MB 593.6 kB/s eta 0:03:11
   --- ----------------------------------- 12.8/125.4 MB 597.1 kB/s eta 0:03:09
   ---- ---------------------------------- 13.1/125.4 MB 600.8 kB/s eta 0:03:07
   ---- ---------------------------------- 13.1/125.4 MB 600.8 kB/s eta 0:03:07
   ---- ---------------------------------- 13.4/125.4 MB 602.7 kB/s eta 0:03:06
   ---- ---------------------------------- 13.6/125.4 MB 605.3 kB/s eta 0:03:05
   ---- ---------------------------------- 13.6/125.4 MB 605.3 kB/s eta 0:03:05
   ---- ---------------------------------- 13.9/125.4 MB 607.8 kB/s eta 0:03:04
   ---- ---------------------------------- 14.2/125.4 MB 612.4 kB/s eta 0:03:02
   ---- ---------------------------------- 14.4/125.4 MB 619.5 kB/s eta 0:03:00
   ---- ---------------------------------- 14.7/125.4 MB 621.9 kB/s eta 0:02:59
   ---- ---------------------------------- 14.7/125.4 MB 621.9 kB/s eta 0:02:59
   ---- ---------------------------------- 14.9/125.4 MB 623.9 kB/s eta 0:02:58
   ---- ---------------------------------- 15.2/125.4 MB 627.0 kB/s eta 0:02:56
   ---- ---------------------------------- 15.5/125.4 MB 631.1 kB/s eta 0:02:55
   ---- ---------------------------------- 15.5/125.4 MB 631.1 kB/s eta 0:02:55
   ---- ---------------------------------- 15.7/125.4 MB 635.7 kB/s eta 0:02:53
   ---- ---------------------------------- 16.0/125.4 MB 637.9 kB/s eta 0:02:52
   ---- ---------------------------------- 16.0/125.4 MB 637.9 kB/s eta 0:02:52
   ----- --------------------------------- 16.3/125.4 MB 638.9 kB/s eta 0:02:51
   ----- --------------------------------- 16.5/125.4 MB 642.8 kB/s eta 0:02:50
   ----- --------------------------------- 16.5/125.4 MB 642.8 kB/s eta 0:02:50
   ----- --------------------------------- 16.8/125.4 MB 641.6 kB/s eta 0:02:50
   ----- --------------------------------- 16.8/125.4 MB 641.6 kB/s eta 0:02:50
   ----- --------------------------------- 17.0/125.4 MB 642.4 kB/s eta 0:02:49
   ----- --------------------------------- 17.3/125.4 MB 645.9 kB/s eta 0:02:48
   ----- --------------------------------- 17.6/125.4 MB 648.6 kB/s eta 0:02:47
   ----- --------------------------------- 17.6/125.4 MB 648.6 kB/s eta 0:02:47
   ----- --------------------------------- 17.6/125.4 MB 648.6 kB/s eta 0:02:47
   ----- --------------------------------- 17.6/125.4 MB 648.6 kB/s eta 0:02:47
   ----- --------------------------------- 18.1/125.4 MB 647.0 kB/s eta 0:02:46
   ----- --------------------------------- 18.1/125.4 MB 647.0 kB/s eta 0:02:46
   ----- --------------------------------- 18.4/125.4 MB 647.7 kB/s eta 0:02:46
   ----- --------------------------------- 18.6/125.4 MB 651.9 kB/s eta 0:02:44
   ----- --------------------------------- 18.9/125.4 MB 653.8 kB/s eta 0:02:43
   ----- --------------------------------- 18.9/125.4 MB 653.8 kB/s eta 0:02:43
   ----- --------------------------------- 19.1/125.4 MB 657.4 kB/s eta 0:02:42
   ------ -------------------------------- 19.4/125.4 MB 661.3 kB/s eta 0:02:41
   ------ -------------------------------- 19.7/125.4 MB 664.7 kB/s eta 0:02:40
   ------ -------------------------------- 19.9/125.4 MB 666.8 kB/s eta 0:02:39
   ------ -------------------------------- 19.9/125.4 MB 666.8 kB/s eta 0:02:39
   ------ -------------------------------- 20.2/125.4 MB 667.3 kB/s eta 0:02:38
   ------ -------------------------------- 20.4/125.4 MB 671.0 kB/s eta 0:02:37
   ------ -------------------------------- 20.7/125.4 MB 674.3 kB/s eta 0:02:36
   ------ -------------------------------- 20.7/125.4 MB 674.3 kB/s eta 0:02:36
   ------ -------------------------------- 21.0/125.4 MB 667.5 kB/s eta 0:02:37
   ------ -------------------------------- 21.2/125.4 MB 672.8 kB/s eta 0:02:35
   ------ -------------------------------- 21.2/125.4 MB 672.8 kB/s eta 0:02:35
   ------ -------------------------------- 21.5/125.4 MB 674.5 kB/s eta 0:02:35
   ------ -------------------------------- 21.8/125.4 MB 677.3 kB/s eta 0:02:34
   ------ -------------------------------- 22.0/125.4 MB 681.7 kB/s eta 0:02:32

In [10]:
import pandas as pd
from autoviz.AutoViz_Class import AutoViz_Class

# Read dataset

df = pd.read_csv("zomato.csv", encoding="latin-1")

# Create AutoViz object

AV = AutoViz_Class()

# Run AutoViz and save plots

dft = AV.AutoViz(
"",
dfte=df,
depVar="",
save_plot_dir="AutoViz_Plots"
)

Shape of your Data Set loaded: (9551, 21)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  3
    Number of Integer-Categorical Columns =  4
    Number of String-Categorical Columns =  3
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  3
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  1
    Number of NLP String Columns =  5
    Number of Date Time Columns =  0
    Number of ID Columns =  1
    Number of Columns to Delete =  1
    21 Predictors classified...
        2 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['Restaurant ID', 'Switch to order menu']
To fix these data quality issues in the dataset, import FixDQ from autoviz...
    All variables classified into correct types.

Number of All Scatter Plots = 6

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package shakespeare to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package stopwords to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package treebank to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package omw to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package wordnet to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package punkt to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection popular

All Plots done
Time to run AutoViz = 155 seconds

 ###################### AUTO VISUALIZATION Completed ########################

In [9]:
!python -m textblob.download_corpora

Finished.

[nltk_data] Downloading package brown to
[nltk_data]     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\brown.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package conll2000 to
[nltk_data]     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\conll2000.zip.
[nltk_data] Downloading package movie_reviews to
[nltk_data]     C:\Users\Anurag\AppData\Roaming\nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!

In [ ]:
# The Best for Automated EDA is